"""Mellinger controller reimplementation based on the Crazyflie firmware.

See https://ieeexplore.ieee.org/document/5980409 for details.
"""

from crazyflow.control.mellinger.control import (
    MellingerAttitudeData,
    MellingerForceTorqueData,
    MellingerStateData,
    attitude2force_torque,
    control_attitude2force_torque,
    control_commit_attitude,
    control_force_torque2rotor_vel,
    control_state2attitude,
    force_torque2rotor_vel,
    state2attitude,
)
from crazyflow.control.mellinger.loss_diagnostics import (
    GAIN_VARIABLE_NAMES,
    GAIN_VARIABLE_SPACE,
    TrackingLossDiagnostics,
    tracking_loss_diagnostics_per_case,
)
from crazyflow.control.mellinger.optimization import (
    COMBINED_MASK,
    TRAIN_INDEX,
    TRAIN_MASK,
    VALIDATION_INDEX,
    VALIDATION_MASK,
    adam_optimization_step,
    evaluate_tracking_objectives,
    select_best_train_checkpoint,
    train_tracking_objective,
    tree_all_finite,
    tree_l2_norm,
    with_controller_mass,
)
from crazyflow.control.mellinger.tracking import (
    GAIN_BOUNDS,
    TRACKING_LOSS_TERM_NAMES,
    GainVariables,
    PositionVelocityGains,
    RolloutTrace,
    TrackingLossConfig,
    TrackingLossTerms,
    aggregate_tracking_metrics,
    apply_gain_variables,
    gain_variables_from_params,
    hover_rotor_velocity,
    initialize_tracking_state,
    physical_gains,
    rollout_state_commands,
    rotor_velocity_limits,
    tracking_loss,
    tracking_loss_per_case,
    tracking_loss_terms_per_case,
    tracking_objective,
    tracking_objective_per_case,
)

__all__ = [
    "COMBINED_MASK",
    "TRAIN_INDEX",
    "TRAIN_MASK",
    "VALIDATION_INDEX",
    "VALIDATION_MASK",
    "adam_optimization_step",
    "evaluate_tracking_objectives",
    "select_best_train_checkpoint",
    "train_tracking_objective",
    "tree_all_finite",
    "tree_l2_norm",
    "with_controller_mass",
    "GAIN_VARIABLE_NAMES",
    "GAIN_VARIABLE_SPACE",
    "TrackingLossDiagnostics",
    "tracking_loss_diagnostics_per_case",
    "state2attitude",
    "attitude2force_torque",
    "force_torque2rotor_vel",
    "MellingerStateData",
    "MellingerAttitudeData",
    "MellingerForceTorqueData",
    "control_state2attitude",
    "control_attitude2force_torque",
    "control_commit_attitude",
    "control_force_torque2rotor_vel",
    "GAIN_BOUNDS",
    "TRACKING_LOSS_TERM_NAMES",
    "GainVariables",
    "PositionVelocityGains",
    "RolloutTrace",
    "TrackingLossConfig",
    "TrackingLossTerms",
    "aggregate_tracking_metrics",
    "gain_variables_from_params",
    "physical_gains",
    "apply_gain_variables",
    "hover_rotor_velocity",
    "initialize_tracking_state",
    "rollout_state_commands",
    "rotor_velocity_limits",
    "tracking_loss",
    "tracking_loss_per_case",
    "tracking_loss_terms_per_case",
    "tracking_objective",
    "tracking_objective_per_case",
]
